// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: textureData.proto

#include "textureData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr textureData_proto::textureData_proto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : filenamedata_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , podata_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , enabled_(0u)
  , texttype_(0)

  , magfilter_(0)

  , minfilter_(0)

  , wraps_(0)

  , wrapt_(0)

  , pixel_type_(0)

  , eformat_(0)

  , ncomponent_(0)

  , width_(0u)
  , height_(0u)
  , component_(0u)
  , bits_(0u)
  , as_is_(0u)
  , filenamesize_(0u)
  , datasize_(0u)
  , hash_(0u){}
struct textureData_protoDefaultTypeInternal {
  constexpr textureData_protoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~textureData_protoDefaultTypeInternal() {}
  union {
    textureData_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT textureData_protoDefaultTypeInternal _textureData_proto_default_instance_;
bool textureData_proto_TEXTURE_EFORMAT_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_EFORMAT_strings[3] = {};

static const char textureData_proto_TEXTURE_EFORMAT_names[] =
  "EFORMAT_BGR"
  "EFORMAT_RGB"
  "EFORMAT_RGBA";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_EFORMAT_entries[] = {
  { {textureData_proto_TEXTURE_EFORMAT_names + 0, 11}, 0 },
  { {textureData_proto_TEXTURE_EFORMAT_names + 11, 11}, 1 },
  { {textureData_proto_TEXTURE_EFORMAT_names + 22, 12}, 2 },
};

static const int textureData_proto_TEXTURE_EFORMAT_entries_by_number[] = {
  0, // 0 -> EFORMAT_BGR
  1, // 1 -> EFORMAT_RGB
  2, // 2 -> EFORMAT_RGBA
};

const std::string& textureData_proto_TEXTURE_EFORMAT_Name(
    textureData_proto_TEXTURE_EFORMAT value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_EFORMAT_entries,
          textureData_proto_TEXTURE_EFORMAT_entries_by_number,
          3, textureData_proto_TEXTURE_EFORMAT_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_EFORMAT_entries,
      textureData_proto_TEXTURE_EFORMAT_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_EFORMAT_strings[idx].get();
}
bool textureData_proto_TEXTURE_EFORMAT_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_EFORMAT* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_EFORMAT_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_EFORMAT>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::EFORMAT_BGR;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::EFORMAT_RGB;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::EFORMAT_RGBA;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::TEXTURE_EFORMAT_MIN;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::TEXTURE_EFORMAT_MAX;
constexpr int textureData_proto::TEXTURE_EFORMAT_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_NCOMPONENT_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_NCOMPONENT_strings[3] = {};

static const char textureData_proto_TEXTURE_NCOMPONENT_names[] =
  "NCOMPONENT_BGR"
  "NCOMPONENT_RGB"
  "NCOMPONENT_RGBA";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_NCOMPONENT_entries[] = {
  { {textureData_proto_TEXTURE_NCOMPONENT_names + 0, 14}, 0 },
  { {textureData_proto_TEXTURE_NCOMPONENT_names + 14, 14}, 1 },
  { {textureData_proto_TEXTURE_NCOMPONENT_names + 28, 15}, 2 },
};

static const int textureData_proto_TEXTURE_NCOMPONENT_entries_by_number[] = {
  0, // 0 -> NCOMPONENT_BGR
  1, // 1 -> NCOMPONENT_RGB
  2, // 2 -> NCOMPONENT_RGBA
};

const std::string& textureData_proto_TEXTURE_NCOMPONENT_Name(
    textureData_proto_TEXTURE_NCOMPONENT value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_NCOMPONENT_entries,
          textureData_proto_TEXTURE_NCOMPONENT_entries_by_number,
          3, textureData_proto_TEXTURE_NCOMPONENT_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_NCOMPONENT_entries,
      textureData_proto_TEXTURE_NCOMPONENT_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_NCOMPONENT_strings[idx].get();
}
bool textureData_proto_TEXTURE_NCOMPONENT_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_NCOMPONENT* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_NCOMPONENT_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_NCOMPONENT>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::NCOMPONENT_BGR;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::NCOMPONENT_RGB;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::NCOMPONENT_RGBA;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::TEXTURE_NCOMPONENT_MIN;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::TEXTURE_NCOMPONENT_MAX;
constexpr int textureData_proto::TEXTURE_NCOMPONENT_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_TYPE_strings[4] = {};

static const char textureData_proto_TEXTURE_TYPE_names[] =
  "BMP"
  "GIF"
  "JPEG"
  "PNG";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_TYPE_entries[] = {
  { {textureData_proto_TEXTURE_TYPE_names + 0, 3}, 2 },
  { {textureData_proto_TEXTURE_TYPE_names + 3, 3}, 3 },
  { {textureData_proto_TEXTURE_TYPE_names + 6, 4}, 0 },
  { {textureData_proto_TEXTURE_TYPE_names + 10, 3}, 1 },
};

static const int textureData_proto_TEXTURE_TYPE_entries_by_number[] = {
  2, // 0 -> JPEG
  3, // 1 -> PNG
  0, // 2 -> BMP
  1, // 3 -> GIF
};

const std::string& textureData_proto_TEXTURE_TYPE_Name(
    textureData_proto_TEXTURE_TYPE value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_TYPE_entries,
          textureData_proto_TEXTURE_TYPE_entries_by_number,
          4, textureData_proto_TEXTURE_TYPE_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_TYPE_entries,
      textureData_proto_TEXTURE_TYPE_entries_by_number,
      4, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_TYPE_strings[idx].get();
}
bool textureData_proto_TEXTURE_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_TYPE* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_TYPE_entries, 4, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_TYPE>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::JPEG;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::PNG;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::BMP;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::GIF;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::TEXTURE_TYPE_MIN;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::TEXTURE_TYPE_MAX;
constexpr int textureData_proto::TEXTURE_TYPE_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_MAG_FILTER_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_MAG_FILTER_strings[2] = {};

static const char textureData_proto_TEXTURE_MAG_FILTER_names[] =
  "MAG_LINEAR"
  "MAG_NEAREST";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_MAG_FILTER_entries[] = {
  { {textureData_proto_TEXTURE_MAG_FILTER_names + 0, 10}, 1 },
  { {textureData_proto_TEXTURE_MAG_FILTER_names + 10, 11}, 0 },
};

static const int textureData_proto_TEXTURE_MAG_FILTER_entries_by_number[] = {
  1, // 0 -> MAG_NEAREST
  0, // 1 -> MAG_LINEAR
};

const std::string& textureData_proto_TEXTURE_MAG_FILTER_Name(
    textureData_proto_TEXTURE_MAG_FILTER value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_MAG_FILTER_entries,
          textureData_proto_TEXTURE_MAG_FILTER_entries_by_number,
          2, textureData_proto_TEXTURE_MAG_FILTER_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_MAG_FILTER_entries,
      textureData_proto_TEXTURE_MAG_FILTER_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_MAG_FILTER_strings[idx].get();
}
bool textureData_proto_TEXTURE_MAG_FILTER_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_MAG_FILTER* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_MAG_FILTER_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_MAG_FILTER>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::MAG_NEAREST;
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::MAG_LINEAR;
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::TEXTURE_MAG_FILTER_MIN;
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::TEXTURE_MAG_FILTER_MAX;
constexpr int textureData_proto::TEXTURE_MAG_FILTER_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_MIN_FILTER_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_MIN_FILTER_strings[6] = {};

static const char textureData_proto_TEXTURE_MIN_FILTER_names[] =
  "MIN_LINEAR"
  "MIN_LINEAR_MIPMAP_LINEAR"
  "MIN_LINEAR_MIPMAP_NEAREST"
  "MIN_NEAREST"
  "MIN_NEAREST_MIPMAP_LINEAR"
  "MIN_NEAREST_MIPMAP_NEAREST";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_MIN_FILTER_entries[] = {
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 0, 10}, 1 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 10, 24}, 5 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 34, 25}, 3 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 59, 11}, 0 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 70, 25}, 4 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 95, 26}, 2 },
};

static const int textureData_proto_TEXTURE_MIN_FILTER_entries_by_number[] = {
  3, // 0 -> MIN_NEAREST
  0, // 1 -> MIN_LINEAR
  5, // 2 -> MIN_NEAREST_MIPMAP_NEAREST
  2, // 3 -> MIN_LINEAR_MIPMAP_NEAREST
  4, // 4 -> MIN_NEAREST_MIPMAP_LINEAR
  1, // 5 -> MIN_LINEAR_MIPMAP_LINEAR
};

const std::string& textureData_proto_TEXTURE_MIN_FILTER_Name(
    textureData_proto_TEXTURE_MIN_FILTER value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_MIN_FILTER_entries,
          textureData_proto_TEXTURE_MIN_FILTER_entries_by_number,
          6, textureData_proto_TEXTURE_MIN_FILTER_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_MIN_FILTER_entries,
      textureData_proto_TEXTURE_MIN_FILTER_entries_by_number,
      6, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_MIN_FILTER_strings[idx].get();
}
bool textureData_proto_TEXTURE_MIN_FILTER_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_MIN_FILTER* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_MIN_FILTER_entries, 6, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_MIN_FILTER>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_NEAREST;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_LINEAR;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_NEAREST_MIPMAP_NEAREST;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_LINEAR_MIPMAP_NEAREST;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_NEAREST_MIPMAP_LINEAR;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_LINEAR_MIPMAP_LINEAR;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::TEXTURE_MIN_FILTER_MIN;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::TEXTURE_MIN_FILTER_MAX;
constexpr int textureData_proto::TEXTURE_MIN_FILTER_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_WRAP_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_WRAP_strings[3] = {};

static const char textureData_proto_TEXTURE_WRAP_names[] =
  "WRAP_CLAMP_TO_EDGE"
  "WRAP_MIRRORED_REPEAT"
  "WRAP_REPEAT";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_WRAP_entries[] = {
  { {textureData_proto_TEXTURE_WRAP_names + 0, 18}, 0 },
  { {textureData_proto_TEXTURE_WRAP_names + 18, 20}, 1 },
  { {textureData_proto_TEXTURE_WRAP_names + 38, 11}, 2 },
};

static const int textureData_proto_TEXTURE_WRAP_entries_by_number[] = {
  0, // 0 -> WRAP_CLAMP_TO_EDGE
  1, // 1 -> WRAP_MIRRORED_REPEAT
  2, // 2 -> WRAP_REPEAT
};

const std::string& textureData_proto_TEXTURE_WRAP_Name(
    textureData_proto_TEXTURE_WRAP value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_WRAP_entries,
          textureData_proto_TEXTURE_WRAP_entries_by_number,
          3, textureData_proto_TEXTURE_WRAP_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_WRAP_entries,
      textureData_proto_TEXTURE_WRAP_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_WRAP_strings[idx].get();
}
bool textureData_proto_TEXTURE_WRAP_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_WRAP* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_WRAP_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_WRAP>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::WRAP_CLAMP_TO_EDGE;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::WRAP_MIRRORED_REPEAT;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::WRAP_REPEAT;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::TEXTURE_WRAP_MIN;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::TEXTURE_WRAP_MAX;
constexpr int textureData_proto::TEXTURE_WRAP_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_PIXEL_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_PIXEL_TYPE_strings[8] = {};

static const char textureData_proto_TEXTURE_PIXEL_TYPE_names[] =
  "BYTE"
  "DOUBLE"
  "FLOAT"
  "INT"
  "SHORT"
  "UNSIGNED_BYTE"
  "UNSIGNED_INT"
  "UNSIGNED_SHORT";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_PIXEL_TYPE_entries[] = {
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 0, 4}, 0 },
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 4, 6}, 7 },
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 10, 5}, 6 },
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 15, 3}, 4 },
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 18, 5}, 2 },
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 23, 13}, 1 },
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 36, 12}, 5 },
  { {textureData_proto_TEXTURE_PIXEL_TYPE_names + 48, 14}, 3 },
};

static const int textureData_proto_TEXTURE_PIXEL_TYPE_entries_by_number[] = {
  0, // 0 -> BYTE
  5, // 1 -> UNSIGNED_BYTE
  4, // 2 -> SHORT
  7, // 3 -> UNSIGNED_SHORT
  3, // 4 -> INT
  6, // 5 -> UNSIGNED_INT
  2, // 6 -> FLOAT
  1, // 7 -> DOUBLE
};

const std::string& textureData_proto_TEXTURE_PIXEL_TYPE_Name(
    textureData_proto_TEXTURE_PIXEL_TYPE value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_PIXEL_TYPE_entries,
          textureData_proto_TEXTURE_PIXEL_TYPE_entries_by_number,
          8, textureData_proto_TEXTURE_PIXEL_TYPE_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_PIXEL_TYPE_entries,
      textureData_proto_TEXTURE_PIXEL_TYPE_entries_by_number,
      8, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_PIXEL_TYPE_strings[idx].get();
}
bool textureData_proto_TEXTURE_PIXEL_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_PIXEL_TYPE* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_PIXEL_TYPE_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_PIXEL_TYPE>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::BYTE;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::UNSIGNED_BYTE;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::SHORT;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::UNSIGNED_SHORT;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::INT;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::UNSIGNED_INT;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::FLOAT;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::DOUBLE;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::TEXTURE_PIXEL_TYPE_MIN;
constexpr textureData_proto_TEXTURE_PIXEL_TYPE textureData_proto::TEXTURE_PIXEL_TYPE_MAX;
constexpr int textureData_proto::TEXTURE_PIXEL_TYPE_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class textureData_proto::_Internal {
 public:
};

textureData_proto::textureData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:textureData_proto)
}
textureData_proto::textureData_proto(const textureData_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  filenamedata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_filenamedata().empty()) {
    filenamedata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_filenamedata(), 
      GetArenaForAllocation());
  }
  podata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_podata().empty()) {
    podata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_podata(), 
      GetArenaForAllocation());
  }
  ::memcpy(&enabled_, &from.enabled_,
    static_cast<size_t>(reinterpret_cast<char*>(&hash_) -
    reinterpret_cast<char*>(&enabled_)) + sizeof(hash_));
  // @@protoc_insertion_point(copy_constructor:textureData_proto)
}

inline void textureData_proto::SharedCtor() {
filenamedata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
podata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&enabled_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&hash_) -
    reinterpret_cast<char*>(&enabled_)) + sizeof(hash_));
}

textureData_proto::~textureData_proto() {
  // @@protoc_insertion_point(destructor:textureData_proto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

inline void textureData_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  filenamedata_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  podata_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void textureData_proto::ArenaDtor(void* object) {
  textureData_proto* _this = reinterpret_cast< textureData_proto* >(object);
  (void)_this;
}
void textureData_proto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void textureData_proto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void textureData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:textureData_proto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filenamedata_.ClearToEmpty();
  podata_.ClearToEmpty();
  ::memset(&enabled_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hash_) -
      reinterpret_cast<char*>(&enabled_)) + sizeof(hash_));
  _internal_metadata_.Clear<std::string>();
}

const char* textureData_proto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 enabled = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          enabled_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_TYPE textType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_texttype(static_cast<::textureData_proto_TEXTURE_TYPE>(val));
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_MAG_FILTER magFilter = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_magfilter(static_cast<::textureData_proto_TEXTURE_MAG_FILTER>(val));
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_MIN_FILTER minFilter = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_minfilter(static_cast<::textureData_proto_TEXTURE_MIN_FILTER>(val));
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_WRAP wrapS = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_wraps(static_cast<::textureData_proto_TEXTURE_WRAP>(val));
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_WRAP wrapT = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_wrapt(static_cast<::textureData_proto_TEXTURE_WRAP>(val));
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_PIXEL_TYPE pixel_type = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_pixel_type(static_cast<::textureData_proto_TEXTURE_PIXEL_TYPE>(val));
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_EFORMAT eFormat = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_eformat(static_cast<::textureData_proto_TEXTURE_EFORMAT>(val));
        } else goto handle_unusual;
        continue;
      // .textureData_proto.TEXTURE_NCOMPONENT nComponent = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_ncomponent(static_cast<::textureData_proto_TEXTURE_NCOMPONENT>(val));
        } else goto handle_unusual;
        continue;
      // uint32 width = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 height = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 component = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 96)) {
          component_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 bits = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 104)) {
          bits_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 as_is = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 112)) {
          as_is_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 fileNameSize = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 120)) {
          filenamesize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes fileNameData = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 130)) {
          auto str = _internal_mutable_filenamedata();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 dataSize = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 136)) {
          datasize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 hash = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 144)) {
          hash_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes poData = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          auto str = _internal_mutable_podata();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* textureData_proto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:textureData_proto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 enabled = 1;
  if (this->_internal_enabled() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_enabled(), target);
  }

  // .textureData_proto.TEXTURE_TYPE textType = 2;
  if (this->_internal_texttype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_texttype(), target);
  }

  // .textureData_proto.TEXTURE_MAG_FILTER magFilter = 3;
  if (this->_internal_magfilter() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_magfilter(), target);
  }

  // .textureData_proto.TEXTURE_MIN_FILTER minFilter = 4;
  if (this->_internal_minfilter() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_minfilter(), target);
  }

  // .textureData_proto.TEXTURE_WRAP wrapS = 5;
  if (this->_internal_wraps() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_wraps(), target);
  }

  // .textureData_proto.TEXTURE_WRAP wrapT = 6;
  if (this->_internal_wrapt() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      6, this->_internal_wrapt(), target);
  }

  // .textureData_proto.TEXTURE_PIXEL_TYPE pixel_type = 7;
  if (this->_internal_pixel_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      7, this->_internal_pixel_type(), target);
  }

  // .textureData_proto.TEXTURE_EFORMAT eFormat = 8;
  if (this->_internal_eformat() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      8, this->_internal_eformat(), target);
  }

  // .textureData_proto.TEXTURE_NCOMPONENT nComponent = 9;
  if (this->_internal_ncomponent() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      9, this->_internal_ncomponent(), target);
  }

  // uint32 width = 10;
  if (this->_internal_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(10, this->_internal_width(), target);
  }

  // uint32 height = 11;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(11, this->_internal_height(), target);
  }

  // uint32 component = 12;
  if (this->_internal_component() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(12, this->_internal_component(), target);
  }

  // uint32 bits = 13;
  if (this->_internal_bits() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(13, this->_internal_bits(), target);
  }

  // uint32 as_is = 14;
  if (this->_internal_as_is() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(14, this->_internal_as_is(), target);
  }

  // uint32 fileNameSize = 15;
  if (this->_internal_filenamesize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(15, this->_internal_filenamesize(), target);
  }

  // bytes fileNameData = 16;
  if (!this->_internal_filenamedata().empty()) {
    target = stream->WriteBytesMaybeAliased(
        16, this->_internal_filenamedata(), target);
  }

  // uint32 dataSize = 17;
  if (this->_internal_datasize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(17, this->_internal_datasize(), target);
  }

  // uint32 hash = 18;
  if (this->_internal_hash() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(18, this->_internal_hash(), target);
  }

  // bytes poData = 19;
  if (!this->_internal_podata().empty()) {
    target = stream->WriteBytesMaybeAliased(
        19, this->_internal_podata(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:textureData_proto)
  return target;
}

size_t textureData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:textureData_proto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes fileNameData = 16;
  if (!this->_internal_filenamedata().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_filenamedata());
  }

  // bytes poData = 19;
  if (!this->_internal_podata().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_podata());
  }

  // uint32 enabled = 1;
  if (this->_internal_enabled() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_enabled());
  }

  // .textureData_proto.TEXTURE_TYPE textType = 2;
  if (this->_internal_texttype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_texttype());
  }

  // .textureData_proto.TEXTURE_MAG_FILTER magFilter = 3;
  if (this->_internal_magfilter() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_magfilter());
  }

  // .textureData_proto.TEXTURE_MIN_FILTER minFilter = 4;
  if (this->_internal_minfilter() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_minfilter());
  }

  // .textureData_proto.TEXTURE_WRAP wrapS = 5;
  if (this->_internal_wraps() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_wraps());
  }

  // .textureData_proto.TEXTURE_WRAP wrapT = 6;
  if (this->_internal_wrapt() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_wrapt());
  }

  // .textureData_proto.TEXTURE_PIXEL_TYPE pixel_type = 7;
  if (this->_internal_pixel_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_pixel_type());
  }

  // .textureData_proto.TEXTURE_EFORMAT eFormat = 8;
  if (this->_internal_eformat() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_eformat());
  }

  // .textureData_proto.TEXTURE_NCOMPONENT nComponent = 9;
  if (this->_internal_ncomponent() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_ncomponent());
  }

  // uint32 width = 10;
  if (this->_internal_width() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_width());
  }

  // uint32 height = 11;
  if (this->_internal_height() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_height());
  }

  // uint32 component = 12;
  if (this->_internal_component() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_component());
  }

  // uint32 bits = 13;
  if (this->_internal_bits() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_bits());
  }

  // uint32 as_is = 14;
  if (this->_internal_as_is() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_as_is());
  }

  // uint32 fileNameSize = 15;
  if (this->_internal_filenamesize() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_filenamesize());
  }

  // uint32 dataSize = 17;
  if (this->_internal_datasize() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_datasize());
  }

  // uint32 hash = 18;
  if (this->_internal_hash() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_hash());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void textureData_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const textureData_proto*>(
      &from));
}

void textureData_proto::MergeFrom(const textureData_proto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:textureData_proto)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filenamedata().empty()) {
    _internal_set_filenamedata(from._internal_filenamedata());
  }
  if (!from._internal_podata().empty()) {
    _internal_set_podata(from._internal_podata());
  }
  if (from._internal_enabled() != 0) {
    _internal_set_enabled(from._internal_enabled());
  }
  if (from._internal_texttype() != 0) {
    _internal_set_texttype(from._internal_texttype());
  }
  if (from._internal_magfilter() != 0) {
    _internal_set_magfilter(from._internal_magfilter());
  }
  if (from._internal_minfilter() != 0) {
    _internal_set_minfilter(from._internal_minfilter());
  }
  if (from._internal_wraps() != 0) {
    _internal_set_wraps(from._internal_wraps());
  }
  if (from._internal_wrapt() != 0) {
    _internal_set_wrapt(from._internal_wrapt());
  }
  if (from._internal_pixel_type() != 0) {
    _internal_set_pixel_type(from._internal_pixel_type());
  }
  if (from._internal_eformat() != 0) {
    _internal_set_eformat(from._internal_eformat());
  }
  if (from._internal_ncomponent() != 0) {
    _internal_set_ncomponent(from._internal_ncomponent());
  }
  if (from._internal_width() != 0) {
    _internal_set_width(from._internal_width());
  }
  if (from._internal_height() != 0) {
    _internal_set_height(from._internal_height());
  }
  if (from._internal_component() != 0) {
    _internal_set_component(from._internal_component());
  }
  if (from._internal_bits() != 0) {
    _internal_set_bits(from._internal_bits());
  }
  if (from._internal_as_is() != 0) {
    _internal_set_as_is(from._internal_as_is());
  }
  if (from._internal_filenamesize() != 0) {
    _internal_set_filenamesize(from._internal_filenamesize());
  }
  if (from._internal_datasize() != 0) {
    _internal_set_datasize(from._internal_datasize());
  }
  if (from._internal_hash() != 0) {
    _internal_set_hash(from._internal_hash());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void textureData_proto::CopyFrom(const textureData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:textureData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool textureData_proto::IsInitialized() const {
  return true;
}

void textureData_proto::InternalSwap(textureData_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &filenamedata_, GetArenaForAllocation(),
      &other->filenamedata_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &podata_, GetArenaForAllocation(),
      &other->podata_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(textureData_proto, hash_)
      + sizeof(textureData_proto::hash_)
      - PROTOBUF_FIELD_OFFSET(textureData_proto, enabled_)>(
          reinterpret_cast<char*>(&enabled_),
          reinterpret_cast<char*>(&other->enabled_));
}

std::string textureData_proto::GetTypeName() const {
  return "textureData_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::textureData_proto* Arena::CreateMaybeMessage< ::textureData_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::textureData_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
